profiles:
  - name: Acoustic
    sequence:
      - RPM: 200
      - Dwell: 20
      - RPM: 400
      - Dwell: 10
      - RPM: 600
      - Dwell: 30
  - name: Break-in
    sequence:
      - RPM: 1000
      - Dwell: 200
      - RPM: 200
      - Dwell: 20
  - name: Grants Profile
    sequence:
      - RPM: 1000
      - Dwell: 200
      - RPM: 200
      - Dwell: 20

