profiles:
  - name: Acoustic
    sequence:
      - RPM: 200
      - Dwell: 25
      - RPM: 400
      - Dwell: 15
      - RPM: 600
      - Dwell: 30
  - name: Break-in
    sequence:
      - RPM: 0
      - Dwell: 5
      - RPM: 400
      - Dwell: 5
      - RPM: 200
      - Dwell: 5
      - RPM: 400
      - Dwell: 5
      - RPM: 200
      - Dwell: 5
  - name: Grants Profile
    sequence:
      - RPM: 1000
      - Dwell: 200
      - RPM: 200
      - Dwell: 20

